### ISSUE TITLE
The contract code couldn't be stored, please check your gas amount.

### ISSUE THREAD

**Issue by nickgeoca** [nickgeoca/crowdfund#1]
```shell
$ truffle migrate --reset
Running migration: 1_initial_migration.js
  Deploying Migrations...
  Migrations: 0x402ed1e007e60a6007a7610d5e6e410cc727c888
Saving successful migration to network...
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying FundingHub...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/home/nickgeoca/.nvm/versions/node/v6.9.2/lib/node_modules/truffle/node_modules/ether-pudding/node_modules/web3/lib/web3/contract.js:147:46)
    at /home/nickgeoca/.nvm/versions/node/v6.9.2/lib/node_modules/truffle/node_modules/ether-pudding/node_modules/web3/lib/web3/method.js:142:25
    at /home/nickgeoca/.nvm/versions/node/v6.9.2/lib/node_modules/truffle/node_modules/ether-pudding/node_modules/web3/lib/web3/requestmanager.js:89:9
    at request.onreadystatechange (/home/nickgeoca/.nvm/versions/node/v6.9.2/lib/node_modules/truffle/node_modules/web3/lib/web3/httpprovider.js:114:13)
    at dispatchEvent (/home/nickgeoca/.nvm/versions/node/v6.9.2/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/home/nickgeoca/.nvm/versions/node/v6.9.2/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/home/nickgeoca/.nvm/versions/node/v6.9.2/lib/node_modules/truffle/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by nickgeoca** [comment]
This error:
 * Error: The contract code couldn't be stored, please check your gas amount.
was caused because the following line threw an error:
```solidity
if (currentTimeUnixTimestamp < block.timestamp) throw;
```
This doesn't make sense because the unix time stamp starts at ~1970 and the block chain timestamp starts at the first epoch (2016 on local net). The unity timestamp should never be less than the block.timestamp.

**Comment by nickgeoca** [comment]
This error
```shell
Error: The contract code couldn't be stored, please check your gas amount. 
```
was caused because the following line threw an error:
```solidity
if (currentTimeUnixTimestamp < block.timestamp) throw;
```
This doesn't make sense because the unix time stamp starts at ~1970 and the block chain timestamp starts at the first epoch (2016 on local net). The unity timestamp should never be less than the block.timestamp.
